---
title: "SCM_Capstone_Code"
author: "Reagan Meagher"
date: "1/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library("Synth")
library("RCurl")
library("dplyr")
```

```{r}
data <- read.csv(text = getURL("https://raw.githubusercontent.com/reagatm/SMU_Capstone/main/treatment_union-7.csv"))
data$Geographic.Area.Name <- as.character(data$Geographic.Area.Name)
```

```{r}
cols <- colnames(data)
cols[-c(1, 2, 145, 146)]
```

```{r}
#"Families_.35.000.to..49.999", "Families_.50.000.to..74.999", "Families_.75.000.to..99.999", "Families_.100.000.to..149.999", "Families_.150.000.to..199.999", "Families_.200.000.or.more", "Families_Median.family.income.dollars", "Families_Mean.family.income.dollars", "Per.capita.income.dollars", "Nonfamily.households", "Median.nonfamily.income.dollars", "Mean.nonfamily.income.dollars", "Median.earnings.for.workers.dollars", "Median.earnings.for.male.full.time..year.round.workers.dollars", "Median.earnings.for.female.full.time..year.round.workers.dollars", "Civilian.noninstitutionalized.population", "With.health.insurance.coverage", "With.health.insurance.coverage_With.private.health.insurance", "With.health.insurance.coverage_With.public.coverage", "No.health.insurance.coverage", "Civilian.noninstitutionalized.population.under.18.years", "Civilian.noninstitutionalized.population.18.to.64.years"

dataprep.out<-
  dataprep(
   foo = data,
   predictors = c("Population.percentile", "Male", "Female", "Under.5.years", "X5.to.9.years", "X10.to.14.years", "X15.to.19.years", "X20.to.24.years", "X25.to.34.years", "X35.to.44.years", "X45.to.54.years", "X55.to.59.years", "X60.to.64.years", "X65.to.74.years", "X75.to.84.years", "X85.years.and.over", "Median.age.years", "X18.years.and.over", "X21.years.and.over", "X62.years.and.over", "X65.years.and.over", "One.race", "Two.or.more.races", "One.race_White", "One.race_Black.or.African.American", "One.race_American.Indian.and.Alaska.Native", "One.race_Asian", "One.race_Asian_Asian.Indian", "One.race_Asian_Chinese", "One.race_Asian_Filipino", "One.race_Asian_Japanese", "One.race_Asian_Korean", "One.race_Asian_Vietnamese", "One.race_Asian_Other.Asian", "One.race_Native.Hawaiian.and.Other.Pacific.Islander", "One.race_Some.other.race", "Two.or.more.races_White.and.Black.or.African.American", "Two.or.more.races_White.and.American.Indian.and.Alaska.Native", "Two.or.more.races_White.and.Asian", "Two.or.more.races_Black.or.African.American.and.American.Indian.and.Alaska.Native", "White", "Black.or.African.American", "American.Indian.and.Alaska.Native", "Asian", "Native.Hawaiian.and.Other.Pacific.Islander", "Some.other.race", "Hispanic.or.Latino.of.any.race", "Hispanic.or.Latino.of.any.race_Mexican", "Hispanic.or.Latino.of.any.race_Puerto.Rican", "Hispanic.or.Latino.of.any.race_Cuban", "Hispanic.or.Latino.of.any.race_Other.Hispanic.or.Latino", "X_Total.housing.units", "Population.16.years.and.over", "In.labor.force", "In.labor.force_Civilian.labor.force_Employed", "In.labor.force_Civilian.labor.force_Unemployed", "In.labor.force_Armed.Forces", "Not.in.labor.force", "Females.16.years.and.over", "X_COMMUTING.TO.WORK_Car..truck..or.van....drove.alone", "X_COMMUTING.TO.WORK_Car..truck..or.van....carpooled", "X_COMMUTING.TO.WORK_Public.transportation.excluding.taxicab", "X_COMMUTING.TO.WORK_Walked", "X_COMMUTING.TO.WORK_Other.means", "X_COMMUTING.TO.WORK_Worked.at.home", "X_COMMUTING.TO.WORK_Mean.travel.time.to.work.minutes", "X_OCCUPATION_Management..business..science..and.arts.occupations", "X_OCCUPATION_Service.occupations", "X_OCCUPATION_Sales.and.office.occupations", "X_OCCUPATION_Natural.resources..construction..and.maintenance.occupations", "X_OCCUPATION_Production..transportation..and.material.moving.occupations", "X_INDUSTRY_Agriculture..forestry..fishing.and.hunting..and.mining", "X_INDUSTRY_Construction", "X_INDUSTRY_Manufacturing", "X_INDUSTRY_Wholesale.trade", "X_INDUSTRY_Retail.trade", "X_INDUSTRY_Transportation.and.warehousing..and.utilities", "X_INDUSTRY_Information", "X_INDUSTRY_Finance.and.insurance..and.real.estate.and.rental.and.leasing", "X_INDUSTRY_Professional..scientific..and.management..and.administrative.and.waste.management.services", "X_INDUSTRY_Educational.services..and.health.care.and.social.assistance", "X_INDUSTRY_Arts..entertainment..and.recreation..and.accommodation.and.food.services", "X_INDUSTRY_Other.services..except.public.administration", "X_INDUSTRY_Public.administration", "X_CLASS.OF.WORKER_Private.wage.and.salary.workers", "X_CLASS.OF.WORKER_Government.workers", "X_CLASS.OF.WORKER_Self.employed.in.own.not.incorporated.business.workers", "X_CLASS.OF.WORKER_Unpaid.family.workers", "Total.households", "Less.than..10.000", "X.10.000.to..14.999", "X.15.000.to..24.999", "X.25.000.to..34.999", "X.35.000.to..49.999", "X.50.000.to..74.999", "X.75.000.to..99.999", "X.100.000.to..149.999", "X.150.000.to..199.999", "X.200.000.or.more", "Median.household.income.dollars", "Mean.household.income.dollars", "With.earnings", "With.earnings_Mean.earnings.dollars", "With.Social.Security", "With.Social.Security_Mean.Social.Security.income.dollars", "With.retirement.income", "With.Supplemental.Security.Income", "With.cash.public.assistance.income", "With.Food.Stamp.SNAP.benefits.in.the.past.12.months", "Families", "Families_Less.than..10.000", "Families_.10.000.to..14.999", "Families_.15.000.to..24.999", "Families_.25.000.to..34.999", "total_votes_x", "republican_vote_percent_x", "democrat_vote_percent_x"),
   dependent = "vote_diff_rep",
   unit.variable = "numid",
   unit.names.variable = "Geographic.Area.Name",
   treatment.identifier = 0,
   controls.identifier = c(1:192, 219:308, 367:438, 443:525, 542:581, 598:635, 719:799, 805:848, 951:1141, 1247:1523, 1542:1572, 1606:1631, 1663:2102, 2108:2216, 2332:2364, 2459:2553, 2577:2663, 2665:2674, 3024:3052, 3067:3162, 3164:3182),
   time.variable = "Year",
   time.predictors.prior = 2012,
   time.optimize.ssr = 2012,
   time.plot = c(2012,2016),
  )
```

```{r}
synth.out <- synth(dataprep.out)
```

```{r}
## there are two ways to summarize the results
## we can either access the output from synth.out directly
round(synth.out$solution.w,2)
# contains the unit weights or
synth.out$solution.v 
## contains the predictor weights. 
```

```{r}
## the output from synth opt 
## can be flexibly combined with 
## the output from dataprep to 
## compute other quantities of interest
## for example, the period by period 
## discrepancies between the 
## treated unit and its synthetic control unit
## can be computed by typing
gaps<- dataprep.out$Y1plot-(
        dataprep.out$Y0plot%*%synth.out$solution.w
        ) ; gaps
```

```{r}
## also there are three convenience functions to summarize results.
## to get summary tables for all information 
## (V and W weights plus balance btw. 
## treated and synthetic control) use the 
## synth.tab() command
synth.tables <- synth.tab(
      dataprep.res = dataprep.out,
      synth.res = synth.out)
print(synth.tables)
```

```{r}
## to get summary plots for outcome trajectories 
## of the treated and the synthetic control unit use the 
## path.plot() and the gaps.plot() commands

## plot in levels (treated and synthetic)
path.plot(dataprep.res = dataprep.out,synth.res = synth.out)
```

